PersonalGram/Controllers/PhotoController.cs
using System.Web.Mvc;
using PersonalGram.Models.Context;
using PersonalGram.Models.PhotoModels;

namespace PersonalGram.Controllers
{
    public class PhotoController : Controller
    {
        PhotoContext _photoContext = new PhotoContext();

        // GET
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UploadPhoto()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadPhoto(Photo photo)
        {
            //Photo photo = new Photo();
            //photo.Content = data;
            _photoContext.Photos.Add(photo);
            return RedirectToAction("Index");
        }
    }
}

PersonalGram/Controllers/UserController.cs
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using PersonalGram.Models;
using PersonalGram.Models.Context;

namespace PersonalGram.Controllers
{
    public class UserController : Controller
    {
        UserContext _userContext = new UserContext();

        /// <summary>
        /// Список пользователей
        /// </summary>
        /// <returns></returns>
        public ActionResult Users()
        {
            var users = _userContext.Users.ToList();
            return View(users);
        }

        /// <summary>
        /// Редактирование пользователей
        /// в карточке пользователя
        /// </summary>
        /// <returns></returns>
        [HttpGet]
        public ActionResult User(int? id)
        {
            if (id == null) return HttpNotFound();
            if (id < 0)
            {
                return View(new User());
            }
            var user = _userContext.Users.FirstOrDefault(p => p.Id == id);
            return View(user);
        }

        [HttpPost]
        public new ActionResult User(User user)
        {
            if (user != null)
            {
                _userContext.Users.AddOrUpdate(user);
                _userContext.SaveChanges();
            }

            return RedirectToAction("Users");
        }

        /// <summary>
        /// Добавление пользователей
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult AddUser(User user)
        {
            _userContext.Users.Add(user);
            _userContext.SaveChanges();
            return RedirectToAction("Users");
        }

        [HttpPost]
        public async Task<ActionResult> DeleteUser(int? id)
        {
            if (id != null)
            {
                var user = _userContext.Users.FirstOrDefault(p => p.Id == id);
                if (user != null)
                {
                    _userContext.Users.Remove(user);
                    await _userContext.SaveChangesAsync();
                    return RedirectToAction("Users");
                }
            }

            return HttpNotFound();
        }
    }
}

PersonalGram/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Blog</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/materialize-script")
    @Styles.Render("~/bundles/materialize-style")
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    @Styles.Render("~/Content/Mytable.css")
</head>
<body>
<nav>
    <div class="nav-wrapper">
        <a href=@Url.Action("Index", "Home") class="brand-logo">Logo</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href=@Url.Action("Users", "User")>Users</a></li>
            <li><a href=@Url.Action("Experiment", "Home")>Experiment </a></li>
            <li><a href=@Url.Action("UploadPhoto", "Photo")>Upload photo</a></li>
        </ul>
    </div>
</nav>

<div class="container body-content">
    @RenderBody()
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>